# Generated by Django 3.1.4 on 2021-01-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bornDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Born date: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone'),
        ),
    ]
