# Generated by Django 3.1.4 on 2021-02-03 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSolicitud', models.DateTimeField(auto_now_add=True)),
                ('FechaArreglo', models.DateTimeField(auto_now=True, null=True)),
                ('Motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('Arreglado', models.BooleanField(default=False)),
                ('IdCoche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.coche', verbose_name='Coche')),
                ('IdDueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to=settings.AUTH_USER_MODEL, verbose_name='Dueno')),
                ('IdMecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to=settings.AUTH_USER_MODEL, verbose_name='Mecanico')),
            ],
        ),
    ]
