# Generated by Django 3.1.4 on 2021-01-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20210128_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
