# Generated by Django 3.1.4 on 2021-01-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(max_length=10, unique=True, verbose_name='Matrícula')),
                ('Marca', models.CharField(blank=True, max_length=50, null=True)),
                ('Modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaMatriculacion', models.DateField(verbose_name='Fecha de la matriculación')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='coches/')),
                ('Dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
        ),
    ]
